var companyList = [
  {
    "Name": "Accent on Independence",
    "Structure": "ESOP",
    "Industry": "Home Care Services",
    "Size": "Denver (Lakewood)",
    "Slogan": "Accent On Independence (AOI) strives to promote independence among people with disabilities and the elderly by providing quality home care services in a safe and effective manner at their place of residence.",
    "Address": "11949 West Colfax Avenue, Lakewood, CO 80215",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(303) 331-0818",
    "Notes": 0
  },
  {
    "Name": "Alpine Banks of Colorado Inc.",
    "Structure": "ESOP",
    "Industry": "Banking",
    "Size": "CO-based (38 locations)",
    "Slogan": "Banking in CO for over 42 years",
    "Address": "2200 Grand Ave. Glenwood Springs, 81601",
    "Contact Name": "Gena Cooper, VP",
    "Contact Email": "genacooper@alpinebank.com",
    "Contact Phone": "970-986-3705",
    "Notes": 0
  },
  {
    "Name": "Alpine Lumber Company",
    "Structure": "ESOP",
    "Industry": "Lumber & Building Materials",
    "Size": "Denver (Westminster)",
    "Slogan": "Employee owned and operated since 1963",
    "Address": "10170 Church Ranch Way, Suite 350, Westminster, 80021",
    "Contact Name": "Mark Morrison or Debra Barnes",
    "Contact Email": "mmorrison@alpinelumber.com",
    "Contact Phone": "303-451-8001",
    "Notes": 0
  },
  {
    "Name": "AmWest Control Inc.",
    "Structure": "ESOP",
    "Industry": "Electrical Engineering",
    "Size": "Denver (Brighton)",
    "Slogan": 0,
    "Address": "10175 E. 106th Ave. Brighton, CO 80601",
    "Contact Name": "Iley Barton",
    "Contact Email": "Iley@amwestcontrol.com",
    "Contact Phone": "303-289-2115",
    "Notes": 0
  },
  {
    "Name": "Aspen Wine Guild",
    "Structure": "Coop",
    "Industry": "Beer, Wine & Spirits",
    "Size": "CO-based (38 locations)",
    "Slogan": "In Colorado since 1975",
    "Address": "319 E. Hopkins Ave. Aspen, CO 81611",
    "Contact Name": "Jeanne C. Doremus",
    "Contact Email": 0,
    "Contact Phone": 0,
    "Notes": 0
  },
  {
    "Name": "Boecore Inc",
    "Structure": "ESOP",
    "Industry": "Employment Agency",
    "Size": "multi-regional",
    "Slogan": "Boecore is a Woman Owned Small Business with over 200 employees developing, operating and maintaining missile defense, space and cyber systems.",
    "Address": "90 S Cascade Ave # 610, Colorado Springs, CO 80903",
    "Contact Name": "Wes Addington",
    "Contact Email": "info@boecore.com",
    "Contact Phone": "(719) 540-5635",
    "Notes": 0
  },
  {
    "Name": "Bradsby Group",
    "Structure": "ESOP",
    "Industry": "Employment Agency/Oil & Gas",
    "Size": "Denver, Houston, Jacksonville",
    "Slogan": "With over 80 recruiters working across a variety of divisions, we offer each of our clients and candidates a complete recruitment solution tailored to their specific needs.",
    "Address": "1700 Broadway, Suite 1500 Denver, CO 80290",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "303-813-8100",
    "Notes": 0
  },
  {
    "Name": "C.B. & Potts Restaurants",
    "Structure": "ESOP (30% employee-owned as of July, 2015)",
    "Industry": "Restaurant & Brewery",
    "Size": "8 locations in CO",
    "Slogan": "Family dining with rotating and seasonal locally brewed beers.",
    "Address": "6575 South Greenwood Plaza Blvd",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(303) 770-1982",
    "Notes": 0
  },
  {
    "Name": "CH2M Hill",
    "Structure": "Stock Incentive & Purchase Plan",
    "Industry": "Engineering Services",
    "Size": "International, 26,000 employees",
    "Slogan": "CH2M Hill is an American engineering company that provides consulting, design, construction, and operations services for corporations, and federal, state, and local governments.",
    "Address": "9191 S. Jamaica St., Englewood, CO 80112",
    "Contact Name": "Jacqueline Hinman",
    "Contact Email": 0,
    "Contact Phone": "720-286-2000",
    "Notes": "I'm pretty sure they are not an esop, but rather a stock-based structure, please verify. (Shawn): I see my error, I hastily included them as ESOP b/c I found them on the NCEO website. Should I still include them on this list, perhaps with a different label, since the NCEO has verified them as an employee owned org? (per the NCEO website: \"To be on the (NCEO) list, companies must be at least 50% owned by an ESOP or other qualified plan or by one or more other kinds of plans in which at least 50% of full-time employees are eligible to participate.)"
  },
  {
    "Name": "Charles D. Jones Company",
    "Structure": "ESOP",
    "Industry": "Heating Equipment Supplier",
    "Size": "Regional",
    "Slogan": "Our commitment is to provide our customers with the highest level of service, technical expertise, training and state-of-the-art technology.",
    "Address": "445 Bryant Street, Denver, CO. 80204",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(303) 922-8426",
    "Notes": 0
  },
  {
    "Name": "Colorado Recovery",
    "Structure": "ESOP",
    "Industry": "Mental Health Services",
    "Size": "Boulder, CO",
    "Slogan": "Colorado Recovery Provides Residential Treatment for Mental Illness that Program Put a Heavy Emphasis on Respect, Social Inclusion, Mutual Support and Optimism.",
    "Address": "1143 Portland Pl. #4, Boulder, 80304",
    "Contact Name": "Dr. David Graybill",
    "Contact Email": "info@coloradorecovery.com",
    "Contact Phone": "303-442-5140",
    "Notes": 0
  },
  {
    "Name": "Community Language Cooperative",
    "Structure": "Coop",
    "Industry": "Translation Services",
    "Size": "Denver-based",
    "Slogan": "The Community Language Cooperative provides interpreting and translation services for nearly any type of event: conferences, business meetings, medical appointments, workshops, and interviews. CLC provides all the necessary equipment for simultaneous interpretation to ensure a seamless and time efficient event.",
    "Address": "4200 Morrison Rd. Denver, 80219",
    "Contact Name": "Indira Guzman-Sais\n, Founder & Interpreter",
    "Contact Email": "info@communitylanguagecoop.com",
    "Contact Phone": "720-394-0126",
    "Notes": 0
  },
  {
    "Name": "Culture Counts",
    "Structure": "ESOP",
    "Industry": "Business Development Service",
    "Size": "Denver-based",
    "Slogan": "Partners on your journey for sustainable change",
    "Address": "600 S. Cherry St. #305, Denver 80246",
    "Contact Name": "Whitney Walpole",
    "Contact Email": "info@culturecounts.biz",
    "Contact Phone": "303-872-7926",
    "Notes": 0
  },
  {
    "Name": "Davey Tree Expert Company",
    "Structure": "ESOP",
    "Industry": "Tree Service",
    "Size": "Nat'l, with local branches. 8,300 employees",
    "Slogan": "Founded in 1880 and employee owned since 1979",
    "Address": "200 S. Quebec St. Denver, CO 80231",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "303-515-7492",
    "Notes": 0
  },
  {
    "Name": "Denver Wholesale Florists",
    "Structure": "ESOP",
    "Industry": "Florist",
    "Size": "Nat'l, with local Headquarters",
    "Slogan": "Where our customers, partners & employees flourish",
    "Address": "4800 Dalia St. Denver, 80216",
    "Contact Name": "David Lisowski, President",
    "Contact Email": "dlisowski@dwfwholesale.com",
    "Contact Phone": "303-399-0970",
    "Notes": 0
  },
  {
    "Name": "Design Works",
    "Structure": "ESOP",
    "Industry": "Florist/Event Services",
    "Size": "Denver-based",
    "Slogan": "Colorado's premier special event provider",
    "Address": "3869 Steele St. Denver, 80205",
    "Contact Name": "Mark Feldmann",
    "Contact Email": "mfeldmann@designworkshop.com",
    "Contact Phone": "720-941-7440",
    "Notes": 0
  },
  {
    "Name": "Drive Train Industries, Inc.",
    "Structure": "ESOP",
    "Industry": "Commercial Auto Parts",
    "Size": "Regional, with local Headquarters",
    "Slogan": "Number one supplier of commercial truck, tractor & trailer parts in the Rocky Mountain Front Range",
    "Address": "5555 Joliet St., Denver 80239",
    "Contact Name": "Jim Burke",
    "Contact Email": "jim.burke@mosaices.com",
    "Contact Phone": "1-800-525-6177",
    "Notes": 0
  },
  {
    "Name": "Elward Systems Corp.",
    "Structure": "ESOP",
    "Industry": "Metal Fabricator",
    "Size": "National, with local Headquarters",
    "Slogan": "Elward Systems Corporation specializes in supplying high quality pre-engineered panel systems utilizing aluminum composite materials (ACM).",
    "Address": "680 N. Harlan St., Lakewood 80214",
    "Contact Name": "James Helgoth",
    "Contact Email": "james.helgoth@elward.com",
    "Contact Phone": "303-239-8719",
    "Notes": 0
  },
  {
    "Name": "Excalibur Associates, Inc.",
    "Structure": "ESOP",
    "Industry": "Environmental Security",
    "Size": "CO & VA",
    "Slogan": "Emergency Management, Health & Safety Management, and Security Services",
    "Address": "8687 WEST 108TH AVENUE, WESTMINSTER, COLORADO 80021",
    "Contact Name": "Charlie Burns",
    "Contact Email": "cburns@excaliburassociates.com",
    "Contact Phone": "888-464-1574",
    "Notes": 0
  },
  {
    "Name": "Facility Logic",
    "Structure": "ESOP",
    "Industry": "Facilities Maintenance/Electrician",
    "Size": "Statewide",
    "Slogan": "FacilityLogic® provides best in class maintenance and construction services to commercial real estate properties.",
    "Address": "12015 E 46th Ave, Suite 200 Denver, CO 80239",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(303) 465-3800",
    "Notes": 0
  },
  {
    "Name": "FirstBank Holding Company",
    "Structure": "ESOP",
    "Industry": "Banking",
    "Size": "Regional, 115 locations in CO, AZ & CA",
    "Slogan": "We owe our success to the core values we’ve held since we were founded in 1963. Ever since, we’ve maintained a strong commitment to convenience, friendly and intelligent customer service, and loyalty to our employees.",
    "Address": "12345 W. Colfax Ave. Lakewood, CO 80215",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(303) 232-3000",
    "Notes": 0
  },
  {
    "Name": "Fort Collins Food Cooperative",
    "Structure": "Coop",
    "Industry": "Grocer",
    "Size": "Ft. Collins, CO",
    "Slogan": "The Coop is a full service grocery store with shelves stocked with the best in local and organic grocery, produce, meats, dairy, household items, pet supplies, health and beauty, and much, much, more.",
    "Address": "250 E Mountain Ave, Fort Collins, CO 80524",
    "Contact Name": 0,
    "Contact Email": "info@fcfood.coop",
    "Contact Phone": "970.484.7448",
    "Notes": 0
  },
  {
    "Name": "General Air",
    "Structure": "ESOP",
    "Industry": "Welding Supply Store",
    "Size": "Statewide",
    "Slogan": "Offering specialty gases for a range of applications, plus welding equipment and classes.",
    "Address": "1105 Zuni St, Denver, CO 80204",
    "Contact Name": "Brett Jones",
    "Contact Email": "bjones@generalair.com",
    "Contact Phone": "(303) 892-7003",
    "Notes": 0
  },
  {
    "Name": "GH Phipps",
    "Structure": "ESOP",
    "Industry": "Construction Company",
    "Size": "Regional",
    "Slogan": "Building Colorado's skyline-- and long-term client relationships-- since 1952",
    "Address": "5995 Greenwood Plaza Blvd, Suite 100\n, Greenwood Village, CO 80111",
    "Contact Name": "Margo Fergusson (Controller)",
    "Contact Email": "margo.ferguson@ghphipps.com",
    "Contact Phone": "1-877-5PHIPPS",
    "Notes": 0
  },
  {
    "Name": "GROUND Engineering Consultants Inc.",
    "Structure": "ESOP",
    "Industry": "Engineering Consultant",
    "Size": "Denver-based",
    "Slogan": "Provides complete pavement analysis and design management services for projects ranging from major interstate highways and airports to parking lots.",
    "Address": "41 Inverness Dr. E. Englewood, 80112",
    "Contact Name": "Jason Goodman",
    "Contact Email": "jasong@groundeng.com",
    "Contact Phone": "(303) 289–1989",
    "Notes": 0
  },
  {
    "Name": "Hazen Research, Inc.",
    "Structure": "ESOP",
    "Industry": "Research, metallurgy/chemical industries",
    "Size": "Golden-based",
    "Slogan": "provides innovative R&D to the mineral, energy, environmental & chemical industries",
    "Address": "4601 Indiana St., Golden 80403",
    "Contact Name": "Bob Rochat",
    "Contact Email": "rochatrs@hazenusa.com",
    "Contact Phone": "303-279-4501",
    "Notes": 0
  },
  {
    "Name": "Henzel Phelps Construction",
    "Structure": "ESOP",
    "Industry": "Construction",
    "Size": "Nation-wide, 2300 Employees",
    "Slogan": "From planning and design, to construction, and facility management, we work to solve our clients’ challenges from start to finish, and beyond.",
    "Address": "420 Sixth Avenue, Greeley, CO 80632",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "970-352-6565",
    "Notes": 0
  },
  {
    "Name": "IMA Financial Group",
    "Structure": "ESOP",
    "Industry": "Insurance & Financial Services",
    "Size": "CO, KS, MI, NY, & TX",
    "Slogan": "The IMA Financial Group, Inc. (100% employee-owned) is a diversified financial services company focused on protecting the assets of its widely varied client base through insurance and wealth management solutions.",
    "Address": "1705 17th Street, Suite 100, Denver, CO 80202",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "303.534.4567",
    "Notes": 0
  },
  {
    "Name": "Intelligent Software Solutions",
    "Structure": "ESOP",
    "Industry": "Data Analysis",
    "Size": "Colorado Springs-based",
    "Slogan": "For both commercial and government organizations, the edge in competitiveness, profit, efficiency and service delivery will be found in the ability to organize, structure and exploit data.",
    "Address": "5450 Tech Center Drive Suite 400, Colorado Springs, CO 80919",
    "Contact Name": "Nikki Herman",
    "Contact Email": "nikki.herman@issinc.com",
    "Contact Phone": 0,
    "Notes": 0
  },
  {
    "Name": "Lamp Rynearson & Associates",
    "Structure": "ESOP",
    "Industry": "Civil Engineering Consulant",
    "Size": "Regional",
    "Slogan": "Founded in 1959, Lamp, Rynearson & Associates has grown to be a multi-disciplinary design firm. Our firm is made up of over 130 talented men and women, providing services from three office locations, Omaha, NE; Fort Collins and Lakewood, CO; and Kansas City, MO.",
    "Address": "4715 Innovation Dr, Fort Collins, CO 80525",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(970) 226-0342",
    "Notes": 0
  },
  {
    "Name": "Larson Distributing Company",
    "Structure": "ESOP",
    "Industry": "Distributor/Wholesaler",
    "Size": "Denver-based",
    "Slogan": "Interior building materials",
    "Address": "5925 Broadway, Denver 80216",
    "Contact Name": "Ginger Hayward",
    "Contact Email": "ghayward@larsondistributing.com",
    "Contact Phone": "303-296-7253",
    "Notes": 0
  },
  {
    "Name": "Leevers Supermarkets Inc.",
    "Structure": "ESOP",
    "Industry": "Grocer",
    "Size": "19 stores, CO & FL",
    "Slogan": "For three generations, Leevers Supermarkets have been bringing low prices and quality products",
    "Address": "2195 N State Hwy 83 #AA, Franktown, CO 80116",
    "Contact Name": "John Leevers, CEO",
    "Contact Email": "johnl@leevers.com",
    "Contact Phone": "(303) 814-8646",
    "Notes": 0
  },
  {
    "Name": "Left Hand Brewing",
    "Structure": "ESOP",
    "Industry": "Brewery",
    "Size": "National, with local Headquarters",
    "Slogan": "A \"Top 50 Craft Brewery\", operating as the 38th craft brewery by volume.",
    "Address": "1265 Boston Ave. Longmont, 80501",
    "Contact Name": 0,
    "Contact Email": "www.lefthandbrewing.com",
    "Contact Phone": "303-772-0258",
    "Notes": 0
  },
  {
    "Name": "Lerch Bates Consultants",
    "Structure": "ESOP",
    "Industry": "Construction Consulting",
    "Size": "National",
    "Slogan": "Global leaders in technical consulting for the building industry",
    "Address": "8089 S Lincoln St # 205, Littleton, CO 80122",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(303) 795-1445",
    "Notes": 0
  },
  {
    "Name": "Les Schwab Tires",
    "Structure": "ESOP",
    "Industry": "Automotive",
    "Size": "Western U.S., 478 locations",
    "Slogan": "Doing the right thing since 1952",
    "Address": "2001 Federal Blvd, Denver, CO 80211",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(303) 455-9424",
    "Notes": 0
  },
  {
    "Name": "LID Landscapes",
    "Structure": "ESOP",
    "Industry": "Landscape Architect",
    "Size": "Boulder County & surrounding areas",
    "Slogan": "An award winning tradition of landscape excellence since 1980",
    "Address": "3131 North 75th Street, Boulder, Colorado 80301",
    "Contact Name": "Stacey Bryant",
    "Contact Email": "s.bryant@lidlandscapes.com",
    "Contact Phone": "(303) 440-7833",
    "Notes": 0
  },
  {
    "Name": "Lundquist Associates Inc.",
    "Structure": "ESOP",
    "Industry": "Construction Company",
    "Size": "Based in Englewood, CO",
    "Slogan": "Established in 1977, Lundquist Associates is committed to providing our customers with \"single source\" quality workmanship to complete projects on time and to meet the ever changing demands of the construction industry.",
    "Address": "2955 S Tejon St, Englewood, CO 80110",
    "Contact Name": "Christiana Sparks",
    "Contact Email": "christiana@lunquist-associates.com",
    "Contact Phone": "(303) 777-0393",
    "Notes": 0
  },
  {
    "Name": "Mayu Meditation Cooperative",
    "Structure": "Coop",
    "Industry": "Meditation Center",
    "Size": "Denver-based",
    "Slogan": "Mayu is your sanctuary for inner transformation",
    "Address": "1804 Pearl St. Denver, CO 80210",
    "Contact Name": 0,
    "Contact Email": "info@mayusanctuary.com",
    "Contact Phone": "303-832-0033",
    "Notes": 0
  },
  {
    "Name": "McStain Enterprises Inc",
    "Structure": "ESOP",
    "Industry": "General Contractor (Construction)",
    "Size": "Denver-based",
    "Slogan": "A COLORADO BASED, PRIVATELY OWNED, NEW CONSTRUCTION BUILDER THAT SPECIALIZES IN CREATING THE BEST HOMEBUILDING EXPERIENCE FOR OUR CUSTOMERS AND THE ENVIRONMENT THROUGH SUSTAINABLE COMMUNITY DESIGNS & HOMEBUILDING PRACTICES.",
    "Address": "7100 Broadway St #5h, Denver, CO 80221",
    "Contact Name": "Lynn Dwyer, HR Mgr.",
    "Contact Email": 0,
    "Contact Phone": "(303) 494-5900",
    "Notes": 0
  },
  {
    "Name": "Merrick & Co",
    "Structure": "ESOP component",
    "Industry": "Banking",
    "Size": "International, with local office",
    "Slogan": "Our Mission at Merrick Bank is to make a positive difference in the lives of our customers, our employees and our community.",
    "Address": "10705 S Jordan Gateway #200, South Jordan, UT 84095",
    "Contact Name": "Jim Gilbert",
    "Contact Email": "jim.gilbert@merrick.com",
    "Contact Phone": "(801) 545-6600",
    "Notes": 0
  },
  {
    "Name": "Metcalf Archaeological Consultants Inc",
    "Structure": "ESOP",
    "Industry": "Archaeology",
    "Size": "Regional",
    "Slogan": "Metcalf Archaeological Consultants, Inc. (MAC) is a 100% employee-owned consulting company that specializes in cultural resource compliance and permitting services.",
    "Address": "651 Corporate Circle, Suite 200, Golden, CO 80401",
    "Contact Name": 0,
    "Contact Email": "mac@metcalfarchaeology.com",
    "Contact Phone": "(303) 425-4507",
    "Notes": 0
  },
  {
    "Name": "Monroe & Newell Engineers Inc.",
    "Structure": "ESOP",
    "Industry": "Structural Engineering",
    "Size": "Colorado-based",
    "Slogan": "Creative individuals sharing one vision.",
    "Address": "1400 Glenarm Pl #101, Denver, CO 80202",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(303) 623-4927",
    "Notes": 0
  },
  {
    "Name": "Muller Engineering",
    "Structure": "Coop",
    "Industry": "Civil Engineering Consulant",
    "Size": "Lakewood, CO, 11 employee-owners",
    "Slogan": "Muller Engineering Company, Inc., is an employee-owned civil engineering consulting firm , formed in 1980.",
    "Address": "777 S. Wadsworth Blvd #4-100, Lakewood, 80226",
    "Contact Name": 0,
    "Contact Email": "www.mullereng.org",
    "Contact Phone": "303-988-4939",
    "Notes": 0
  },
  {
    "Name": "MWH Global",
    "Structure": "ESOP",
    "Industry": "Water & Natural Resources",
    "Size": "International, 180 offices, 7,000 employees",
    "Slogan": "The Global Leader in Wastewater Engineering.",
    "Address": "1560 Broadway St #1800, Denver, CO 80202",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(303) 291-2222",
    "Notes": 0
  },
  {
    "Name": "Namaste Solar",
    "Structure": "Coop",
    "Industry": "Solar Energy Equipment Supply",
    "Size": "CO, NY & CA",
    "Slogan": "Namasté Solar, founded in 2005, is your quality solar partner helping you reduce energy costs and meet your sustainability goals",
    "Address": "4571 Broadway Street, Boulder, Colorado 80304",
    "Contact Name": "Blake Jones",
    "Contact Email": "info@namastesolar.com",
    "Contact Phone": "(303) 447-0300",
    "Notes": 0
  },
  {
    "Name": "Neenan Archistruction",
    "Structure": "ESOP",
    "Industry": "Architect",
    "Size": "Denver/Ft. Collins",
    "Slogan": "Integrated real estate, development, architecture and construction in Denver and Fort Collins.",
    "Address": "2607 Midpoint Dr, Fort Collins, CO 80525",
    "Contact Name": "Ryan Dellos",
    "Contact Email": "ryan.dellos@neenan.com",
    "Contact Phone": "(970) 493-8747",
    "Notes": 0
  },
  {
    "Name": "New Belgium Brewing",
    "Structure": "ESOP",
    "Industry": "Brewery",
    "Size": "4th largest craft brewery in the US",
    "Slogan": "New Belgium Brewing Company is a craft brewery located in Fort Collins, Colorado. It opened in 1991 after Jeff Lebesch, the brewery's founder, took his homebrewing passion commercially. In 2011, it produced 712,800 barrels of its various labels.",
    "Address": "500 Linden Street\nFort Collins, CO 80524",
    "Contact Name": "Jenny Briggs",
    "Contact Email": "jbriggs@newbelgium.com",
    "Contact Phone": "970-221-0524",
    "Notes": 0
  },
  {
    "Name": "North Park Transportation Company",
    "Structure": "ESOP",
    "Industry": "Trucking",
    "Size": "CO & Regional",
    "Slogan": "North Park Transportation Co. provides quality less-than-truckload service to a six state region.",
    "Address": "5150 Columbine St, Denver, CO 80216",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(303) 295-0300",
    "Notes": 0
  },
  {
    "Name": "Odell Brewing",
    "Structure": "ESOP",
    "Industry": "Brewery",
    "Size": "34th largest craft brewery",
    "Slogan": "Odell Brewing is now the 34th largest craft brewery in the country distributing beer to just 11 states and a small amount into the UK.",
    "Address": "800 E. Lincoln Ave. Ft. Collins, 80524",
    "Contact Name": 0,
    "Contact Email": "www.odellbrewing.com",
    "Contact Phone": "970-498-9070",
    "Notes": 0
  },
  {
    "Name": "Ohlson Lavoie Collaborative",
    "Structure": "ESOP",
    "Industry": "Architecture, Aquatics, Interiors",
    "Size": "International",
    "Slogan": "Ohlson Lavoie Collaborative (OLC) is comprised of planners and designers who listen, understand, guide and create",
    "Address": "616 E Speer Blvd, Denver, CO 80203",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(303) 294-9244",
    "Notes": 0
  },
  {
    "Name": "P&L Printing",
    "Structure": "Coop",
    "Industry": "Commercial Printing",
    "Size": "Denver-based",
    "Slogan": "For over three decades, P&L has been worker owned and operated, serving the needs of: non-profits, unions, businesses, community organizers, co-ops, musicians, & individuals.",
    "Address": "3827 Steele St. Unit E Denver, CO 80205",
    "Contact Name": 0,
    "Contact Email": "plprinting@msn.com",
    "Contact Phone": "303.433.1852",
    "Notes": 0
  },
  {
    "Name": "Payzone Directional Services",
    "Structure": "ESOP",
    "Industry": "Drilling Contractor",
    "Size": "Regional/National",
    "Slogan": "Payzone Directional Services (PDS) has been delivering industry-leading service quality to our energy partners since 2006. The company launched initial operations in the Rocky Mountain region, and has since branched out to service all major basins across the lower 48.",
    "Address": "700 17th Street, Suite 900 Denver CO 80202",
    "Contact Name": 0,
    "Contact Email": "info@payzonedirectional.com",
    "Contact Phone": "303-876-6240",
    "Notes": 0
  },
  {
    "Name": "PCL Construction",
    "Structure": "ESOP",
    "Industry": "Industrial Construction",
    "Size": "Int'l",
    "Slogan": "The PCL family of construction companies are general constructioncontractors in the buildings, civil, and heavy industrial markets",
    "Address": "2000 S Colorado Blvd, Denver, CO 80222",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(303) 365-6500",
    "Notes": 0
  },
  {
    "Name": "Pester Marketing",
    "Structure": "ESOP",
    "Industry": "Convenience Stores",
    "Size": "Regional",
    "Slogan": "Pester Marketing Company owns and operates a number of convenience stores situated in New Mexico, Colorado, Kansas and Nebraska.",
    "Address": "4643 S Ulster St #350, Denver, CO 80237",
    "Contact Name": "Terry Lacy",
    "Contact Email": "tlacy@pestermarketing.com",
    "Contact Phone": "(303) 693-9331",
    "Notes": 0
  },
  {
    "Name": "Pipe Valve & Fitting Company",
    "Structure": "employee owned",
    "Industry": "Pipe Supplier",
    "Size": "CO & UT",
    "Slogan": "Celebrating 52 years in business. A Colorado and Utah employee-owned company.",
    "Address": "2505 E 79th Ave, Denver, CO 80229",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(303) 289-5811",
    "Notes": 0
  },
  {
    "Name": "Polar Field Services",
    "Structure": "ESOP",
    "Industry": "Project Management/Logistics",
    "Size": "Denver/Int'l",
    "Slogan": "Polar Field Services, a woman-owned small business and an employee-owned company, delivers full-cycle project management, facilities support and logistics services to customers in remote locations.",
    "Address": "8100 Shaffer Parkway, Suite 100, Littleton CO",
    "Contact Name": "Jill Ferris",
    "Contact Email": "info@polarfield.com",
    "Contact Phone": "303.984.1450",
    "Notes": 0
  },
  {
    "Name": "Power Zone",
    "Structure": "ESOP",
    "Industry": "Industrial Equipment Supplier",
    "Size": "Colorado-based",
    "Slogan": "Power Zone Equipment sells and packages industrial pumps including duplex, triplex, and quintuplex plunger pumps as well as piston pumps.",
    "Address": "46920 Co Rd E, Center, CO 81125",
    "Contact Name": "Brian Garrison",
    "Contact Email": 0,
    "Contact Phone": "(719) 754-1981",
    "Notes": 0
  },
  {
    "Name": "RAM International (includes C.B. & Potts)",
    "Structure": "ESOP",
    "Industry": "Restaurants & Breweries",
    "Size": "Int'l, with CO locations",
    "Slogan": "Washington-based RAM restaurants, owner of 6 Colorado locations (C.B. & Potts), was sold to 65% of its workforce (about 2000 employees) through an ESOP.",
    "Address": "Ram International, P.O. BOX 98768, Lakewood, WA 98496",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "253.588.1788",
    "Notes": 0
  },
  {
    "Name": "Re/Max of Cherry Creek",
    "Structure": "broker-owned",
    "Industry": "Real Estate Agency",
    "Size": "Denver",
    "Slogan": "Because Experience Matters",
    "Address": "3773 Cherry Creek North Drive, #801",
    "Contact Name": 0,
    "Contact Email": "info@rmcherrycreek.com",
    "Contact Phone": "303-320-1556",
    "Notes": 0
  },
  {
    "Name": "Ready Talk",
    "Structure": "ESOP",
    "Industry": "Software Company",
    "Size": "Denver-based",
    "Slogan": "Delivers audio conferencing, web conferencing and webinar technology.",
    "Address": "1900 16th St #600, Denver, CO 80202",
    "Contact Name": "Dan Grote, CFO",
    "Contact Email": "dan.grote@readytalk.com",
    "Contact Phone": "303-209-1700",
    "Notes": 0
  },
  {
    "Name": "RESPEC Consulting",
    "Structure": "ESOP (100%)",
    "Industry": "Mining, Natural Resources",
    "Size": "National, 210+ employees",
    "Slogan": "Since our founding in 1969, RESPEC has remained committed to its original purpose of providing clients with high-quality technical and advisory services.",
    "Address": "720 South Colorado Blvd. Suite 410 S \n Denver, CO 80246",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "303-757-3655",
    "Notes": 0
  },
  {
    "Name": "RNL Design",
    "Structure": "ESOP",
    "Industry": "Architect",
    "Size": "Regional",
    "Slogan": "RNL is a multi-disciplined architecture, interior design and engineering firm with offices in Denver, Los Angeles, and Phoenix.",
    "Address": "1050 17th St #A200, , Denver, CO 80265",
    "Contact Name": "Josh Gould, CEO",
    "Contact Email": "josh.gould@rnldesign.com",
    "Contact Phone": "303-921-8359",
    "Notes": 0
  },
  {
    "Name": "Rocky Mountain Employee Ownership Center",
    "Structure": "(nonprofit supporting ESOPS & Co-ops)",
    "Industry": "Nonprofit",
    "Size": "Statewide",
    "Slogan": "RMEOC stimulates employee-ownership opportunities within the Rocky Mountain region in the form of ESOPs and Worker Coops.",
    "Address": "383 Corona St.,  Denver, CO 80218",
    "Contact Name": "Jeff Ambs",
    "Contact Email": "info@rmeoc.org",
    "Contact Phone": "303.351.2003",
    "Notes": 0
  },
  {
    "Name": "Roth Distributing",
    "Structure": "ESOP",
    "Industry": "Appliance Store",
    "Size": "Regional",
    "Slogan": "Upscale kitchen-appliance outpost with a spacious showroom featuring brand-name products.",
    "Address": "17801 E 40th Ave, Aurora, CO 80011",
    "Contact Name": "Jon Thielen, CEO",
    "Contact Email": "johnt@rothdistributing.com",
    "Contact Phone": "(303) 373-9090",
    "Notes": 0
  },
  {
    "Name": "S.A. Miro Inc.",
    "Structure": "ESOP",
    "Industry": "Engineering Consultant",
    "Size": "Denver & Abu Dhabi-based",
    "Slogan": "Miro has a particular expertise in the development of cost-effective buildings that use a mix of materials to achieve a variety of functional objectives.",
    "Address": "4582 S. Ulster Street \nSuite 300,\nDenver, CO 80237",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "303-741-3737",
    "Notes": 0
  },
  {
    "Name": "San Juan Construction",
    "Structure": "ESOP",
    "Industry": "Building Construction",
    "Size": "Int'l",
    "Slogan": "We are a multi-disciplined construction company having completed projects in Alaska, California, Colorado, Hawaii, North Carolina, Washington and the outer Pacific and Indian Ocean islands.",
    "Address": "401 E Main St, Montrose, CO 81401",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(970) 497-8200",
    "Notes": 0
  },
  {
    "Name": "Stailey Insurance",
    "Structure": "ESOP",
    "Industry": "Insurance Agency",
    "Size": "Denver-based",
    "Slogan": "Enjoying the freedom and mobility your vehicle provides is part and parcel of the American dream. Our job is to help you protect that dream.",
    "Address": "2084 S Milwaukee St, Denver, CO 80210",
    "Contact Name": "Grant Stailey",
    "Contact Email": "grant@staileycorp.com",
    "Contact Phone": "(303) 647-5757",
    "Notes": 0
  },
  {
    "Name": "Stoneage Inc.",
    "Structure": "ESOP",
    "Industry": "Water Jet Engineering",
    "Size": "Int'l--HQ in Durango, CO",
    "Slogan": "StoneAge is now recognized as a world leader in providing tools and equipment for water blast cleaning.",
    "Address": "466 S Skylane Dr, Durango, CO 81303",
    "Contact Name": "Amy Moody",
    "Contact Email": "sales@stoneagetools.com",
    "Contact Phone": "(970) 259-2869",
    "Notes": 0
  },
  {
    "Name": "STORserver Inc.",
    "Structure": "employee owned",
    "Industry": "Computer Software Store",
    "Size": "Colo.Springs- based",
    "Slogan": "STORServer offers the only built-to-order backup appliance for enterprises",
    "Address": "B, 485 Elkton Dr, Colorado Springs, CO 80907",
    "Contact Name": 0,
    "Contact Email": "requestinfo@storserver.com",
    "Contact Phone": "(719) 266-8777",
    "Notes": 0
  },
  {
    "Name": "The Group Real Estate Co",
    "Structure": "Stock ownership",
    "Industry": "Real estate company",
    "Size": "northern CO",
    "Slogan": "The Group, Inc. has been the Northern Colorado market leader for over 30 years and we remain committed to our mission of “helping people get where they want to go on time.”",
    "Address": "375 E Horsetooth Road, Fort Collins, Colorado 80525",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "970-223-0700",
    "Notes": 0
  },
  {
    "Name": "Trinidad Benham Corporation",
    "Structure": "ESOP",
    "Industry": "Merchandising/Distribution",
    "Size": "National, with CO office",
    "Slogan": "Trinidad Benham is a merchandising, packaging, trading and distribution company driven by experienced employee-owners. We’re known for beans, rice, popcorn and aluminum foil, but we’re so much more.",
    "Address": "3650 S. Yosemite, Suite 300, P.O. Box 378007 Denver, 80237",
    "Contact Name": "Gary Peters, CEO",
    "Contact Email": "gpeters@trinidadbenham.com",
    "Contact Phone": "(303) 220-1400",
    "Notes": 0
  },
  {
    "Name": "Union Taxi Cooperative",
    "Structure": "Coop",
    "Industry": "Taxi Service",
    "Size": "Denver-based",
    "Slogan": "Union Taxi Cooperatives is a driver-owned taxi fleet where each driver has a personal stake in providing exemplary service.",
    "Address": "2840 S Vallejo St, Englewood, CO 80110",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "303-922-2222",
    "Notes": 0
  },
  {
    "Name": "Venoco Inc.",
    "Structure": "ESOP",
    "Industry": "Investment Service",
    "Size": "CO & CA-based",
    "Slogan": "Venoco, Inc. is an independent energy company engaged in the acquisition, exploration and development of oil and natural gas properties",
    "Address": "370 17th St #3900, Denver, CO 80202",
    "Contact Name": "Beth Behnke, HR Mgr.",
    "Contact Email": "bbehnke@venocoinc.com",
    "Contact Phone": "(303) 626-8300",
    "Notes": 0
  },
  {
    "Name": "Vision Care Specialists",
    "Structure": "ESOP",
    "Industry": "Optometrist",
    "Size": "5 locations in Metro-Denver",
    "Slogan": "Since 1974, our Colorado eye doctors have been using the latest technologies to provide the highest quality of care.",
    "Address": "6160 S Syracuse Way, Greenwood Village, CO 80111",
    "Contact Name": "Cully Holmes, HR Mgr.",
    "Contact Email": "homlesc@vcseye.com",
    "Contact Phone": "(303) 298-9398",
    "Notes": 0
  },
  {
    "Name": "Wheatridge Pharmacy",
    "Structure": "ESOP",
    "Industry": "Pharmacy",
    "Size": "Wheatridge, CO",
    "Slogan": "We offer the highest level of pharmaceutical care, as well as, exceptional customer service. You and your family will become a recognized name and face here at Wheat Ridge Pharmacy.",
    "Address": "6650 W. 38th Ave. Wheatridge, 80033",
    "Contact Name": "Wendy (employee-owner)",
    "Contact Email": "www.wrpharmacy.com",
    "Contact Phone": "303-421-6111",
    "Notes": 0
  },
  {
    "Name": "Wright Water Engineers",
    "Structure": "employee owned",
    "Industry": "Engineering Consultant",
    "Size": "Colorado-based",
    "Slogan": "Provides a broad range of specialized planning and engineering services.",
    "Address": "2490 W 26th Ave # 100A, Denver, CO 80211",
    "Contact Name": 0,
    "Contact Email": 0,
    "Contact Phone": "(303) 480-1700",
    "Notes": 0
  },
  {
    "Name": "Yenter Companies Inc.",
    "Structure": "ESOP",
    "Industry": "Excavating Contractor",
    "Size": "Colorado-based",
    "Slogan": "Yenter Companies has been handling the most difficult and challenging drilling and blasting projects for over 35 years",
    "Address": "20300 CO-72, Arvada, CO 80007",
    "Contact Name": "David McKinley",
    "Contact Email": "dmckinley@yenter.com",
    "Contact Phone": "(303) 279-4458",
    "Notes": 0
  },
  {
    "Name": "Zick Business Advisors Inc.",
    "Structure": "ESOP",
    "Industry": "Accounting",
    "Size": "Denver",
    "Slogan": "Zick Business Advisors, Inc. is a Colorado professional corporation of Certified Public Accountants and Certified Valuation Analysts, founded in 1971.",
    "Address": "16 Inverness Pl E # C, Englewood, CO 80112",
    "Contact Name": 0,
    "Contact Email": "info@zickcpa.com",
    "Contact Phone": "(303) 758-9167",
    "Notes": 0
  }
];
